// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProjectInformation struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directory            string   `protobuf:"bytes,2,opt,name=directory,proto3" json:"directory,omitempty"`
	WioPath              string   `protobuf:"bytes,3,opt,name=wioPath,proto3" json:"wioPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectInformation) Reset()         { *m = ProjectInformation{} }
func (m *ProjectInformation) String() string { return proto.CompactTextString(m) }
func (*ProjectInformation) ProtoMessage()    {}
func (*ProjectInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{0}
}
func (m *ProjectInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectInformation.Unmarshal(m, b)
}
func (m *ProjectInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectInformation.Marshal(b, m, deterministic)
}
func (dst *ProjectInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectInformation.Merge(dst, src)
}
func (m *ProjectInformation) XXX_Size() int {
	return xxx_messageInfo_ProjectInformation.Size(m)
}
func (m *ProjectInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectInformation.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectInformation proto.InternalMessageInfo

func (m *ProjectInformation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectInformation) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *ProjectInformation) GetWioPath() string {
	if m != nil {
		return m.WioPath
	}
	return ""
}

type DependencyLinkTarget struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Visibility           string   `protobuf:"bytes,3,opt,name=visibility,proto3" json:"visibility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependencyLinkTarget) Reset()         { *m = DependencyLinkTarget{} }
func (m *DependencyLinkTarget) String() string { return proto.CompactTextString(m) }
func (*DependencyLinkTarget) ProtoMessage()    {}
func (*DependencyLinkTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{1}
}
func (m *DependencyLinkTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyLinkTarget.Unmarshal(m, b)
}
func (m *DependencyLinkTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyLinkTarget.Marshal(b, m, deterministic)
}
func (dst *DependencyLinkTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyLinkTarget.Merge(dst, src)
}
func (m *DependencyLinkTarget) XXX_Size() int {
	return xxx_messageInfo_DependencyLinkTarget.Size(m)
}
func (m *DependencyLinkTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyLinkTarget.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyLinkTarget proto.InternalMessageInfo

func (m *DependencyLinkTarget) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DependencyLinkTarget) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *DependencyLinkTarget) GetVisibility() string {
	if m != nil {
		return m.Visibility
	}
	return ""
}

type DependencyTarget struct {
	Name                  string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                  string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Flags                 []string `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	Definitions           []string `protobuf:"bytes,4,rep,name=definitions,proto3" json:"definitions,omitempty"`
	FlagsVisibility       string   `protobuf:"bytes,5,opt,name=flagsVisibility,proto3" json:"flagsVisibility,omitempty"`
	DefinitionsVisibility string   `protobuf:"bytes,6,opt,name=definitionsVisibility,proto3" json:"definitionsVisibility,omitempty"`
	HeaderOnly            bool     `protobuf:"varint,7,opt,name=headerOnly,proto3" json:"headerOnly,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *DependencyTarget) Reset()         { *m = DependencyTarget{} }
func (m *DependencyTarget) String() string { return proto.CompactTextString(m) }
func (*DependencyTarget) ProtoMessage()    {}
func (*DependencyTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{2}
}
func (m *DependencyTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyTarget.Unmarshal(m, b)
}
func (m *DependencyTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyTarget.Marshal(b, m, deterministic)
}
func (dst *DependencyTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyTarget.Merge(dst, src)
}
func (m *DependencyTarget) XXX_Size() int {
	return xxx_messageInfo_DependencyTarget.Size(m)
}
func (m *DependencyTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyTarget.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyTarget proto.InternalMessageInfo

func (m *DependencyTarget) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DependencyTarget) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DependencyTarget) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *DependencyTarget) GetDefinitions() []string {
	if m != nil {
		return m.Definitions
	}
	return nil
}

func (m *DependencyTarget) GetFlagsVisibility() string {
	if m != nil {
		return m.FlagsVisibility
	}
	return ""
}

func (m *DependencyTarget) GetDefinitionsVisibility() string {
	if m != nil {
		return m.DefinitionsVisibility
	}
	return ""
}

func (m *DependencyTarget) GetHeaderOnly() bool {
	if m != nil {
		return m.HeaderOnly
	}
	return false
}

type TargetInformation struct {
	ProjectInformation   *ProjectInformation          `protobuf:"bytes,1,opt,name=projectInformation,proto3" json:"projectInformation,omitempty"`
	TargetName           string                       `protobuf:"bytes,2,opt,name=targetName,proto3" json:"targetName,omitempty"`
	TargetPath           string                       `protobuf:"bytes,3,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	Platform             string                       `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Framework            string                       `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	Hardware             string                       `protobuf:"bytes,6,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Flags                []string                     `protobuf:"bytes,7,rep,name=flags,proto3" json:"flags,omitempty"`
	Definitions          []string                     `protobuf:"bytes,8,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Dependencies         map[string]*DependencyTarget `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DependenciesLink     []*DependencyLinkTarget      `protobuf:"bytes,10,rep,name=dependenciesLink,proto3" json:"dependenciesLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TargetInformation) Reset()         { *m = TargetInformation{} }
func (m *TargetInformation) String() string { return proto.CompactTextString(m) }
func (*TargetInformation) ProtoMessage()    {}
func (*TargetInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{3}
}
func (m *TargetInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetInformation.Unmarshal(m, b)
}
func (m *TargetInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetInformation.Marshal(b, m, deterministic)
}
func (dst *TargetInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetInformation.Merge(dst, src)
}
func (m *TargetInformation) XXX_Size() int {
	return xxx_messageInfo_TargetInformation.Size(m)
}
func (m *TargetInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetInformation.DiscardUnknown(m)
}

var xxx_messageInfo_TargetInformation proto.InternalMessageInfo

func (m *TargetInformation) GetProjectInformation() *ProjectInformation {
	if m != nil {
		return m.ProjectInformation
	}
	return nil
}

func (m *TargetInformation) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *TargetInformation) GetTargetPath() string {
	if m != nil {
		return m.TargetPath
	}
	return ""
}

func (m *TargetInformation) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *TargetInformation) GetFramework() string {
	if m != nil {
		return m.Framework
	}
	return ""
}

func (m *TargetInformation) GetHardware() string {
	if m != nil {
		return m.Hardware
	}
	return ""
}

func (m *TargetInformation) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *TargetInformation) GetDefinitions() []string {
	if m != nil {
		return m.Definitions
	}
	return nil
}

func (m *TargetInformation) GetDependencies() map[string]*DependencyTarget {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *TargetInformation) GetDependenciesLink() []*DependencyLinkTarget {
	if m != nil {
		return m.DependenciesLink
	}
	return nil
}

type Executable struct {
	CommandName          string   `protobuf:"bytes,1,opt,name=commandName,proto3" json:"commandName,omitempty"`
	CommandArguments     []string `protobuf:"bytes,2,rep,name=commandArguments,proto3" json:"commandArguments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Executable) Reset()         { *m = Executable{} }
func (m *Executable) String() string { return proto.CompactTextString(m) }
func (*Executable) ProtoMessage()    {}
func (*Executable) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{4}
}
func (m *Executable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Executable.Unmarshal(m, b)
}
func (m *Executable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Executable.Marshal(b, m, deterministic)
}
func (dst *Executable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Executable.Merge(dst, src)
}
func (m *Executable) XXX_Size() int {
	return xxx_messageInfo_Executable.Size(m)
}
func (m *Executable) XXX_DiscardUnknown() {
	xxx_messageInfo_Executable.DiscardUnknown(m)
}

var xxx_messageInfo_Executable proto.InternalMessageInfo

func (m *Executable) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *Executable) GetCommandArguments() []string {
	if m != nil {
		return m.CommandArguments
	}
	return nil
}

type Executables struct {
	Executables          []*Executable `protobuf:"bytes,1,rep,name=executables,proto3" json:"executables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Executables) Reset()         { *m = Executables{} }
func (m *Executables) String() string { return proto.CompactTextString(m) }
func (*Executables) ProtoMessage()    {}
func (*Executables) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{5}
}
func (m *Executables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Executables.Unmarshal(m, b)
}
func (m *Executables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Executables.Marshal(b, m, deterministic)
}
func (dst *Executables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Executables.Merge(dst, src)
}
func (m *Executables) XXX_Size() int {
	return xxx_messageInfo_Executables.Size(m)
}
func (m *Executables) XXX_DiscardUnknown() {
	xxx_messageInfo_Executables.DiscardUnknown(m)
}

var xxx_messageInfo_Executables proto.InternalMessageInfo

func (m *Executables) GetExecutables() []*Executable {
	if m != nil {
		return m.Executables
	}
	return nil
}

type RunInformation struct {
	TargetName           string   `protobuf:"bytes,1,opt,name=targetName,proto3" json:"targetName,omitempty"`
	HardwarePort         string   `protobuf:"bytes,2,opt,name=hardwarePort,proto3" json:"hardwarePort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunInformation) Reset()         { *m = RunInformation{} }
func (m *RunInformation) String() string { return proto.CompactTextString(m) }
func (*RunInformation) ProtoMessage()    {}
func (*RunInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_platform_90d570a7a17b69c4, []int{6}
}
func (m *RunInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunInformation.Unmarshal(m, b)
}
func (m *RunInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunInformation.Marshal(b, m, deterministic)
}
func (dst *RunInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunInformation.Merge(dst, src)
}
func (m *RunInformation) XXX_Size() int {
	return xxx_messageInfo_RunInformation.Size(m)
}
func (m *RunInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_RunInformation.DiscardUnknown(m)
}

var xxx_messageInfo_RunInformation proto.InternalMessageInfo

func (m *RunInformation) GetTargetName() string {
	if m != nil {
		return m.TargetName
	}
	return ""
}

func (m *RunInformation) GetHardwarePort() string {
	if m != nil {
		return m.HardwarePort
	}
	return ""
}

func init() {
	proto.RegisterType((*ProjectInformation)(nil), "proto.ProjectInformation")
	proto.RegisterType((*DependencyLinkTarget)(nil), "proto.DependencyLinkTarget")
	proto.RegisterType((*DependencyTarget)(nil), "proto.DependencyTarget")
	proto.RegisterType((*TargetInformation)(nil), "proto.TargetInformation")
	proto.RegisterMapType((map[string]*DependencyTarget)(nil), "proto.TargetInformation.DependenciesEntry")
	proto.RegisterType((*Executable)(nil), "proto.Executable")
	proto.RegisterType((*Executables)(nil), "proto.Executables")
	proto.RegisterType((*RunInformation)(nil), "proto.RunInformation")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlatformClient is the client API for Platform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlatformClient interface {
	CreateExampleProject(ctx context.Context, in *ProjectInformation, opts ...grpc.CallOption) (*Executables, error)
	BuildProject(ctx context.Context, in *TargetInformation, opts ...grpc.CallOption) (*Executables, error)
	RunProject(ctx context.Context, in *RunInformation, opts ...grpc.CallOption) (*Executables, error)
}

type platformClient struct {
	cc *grpc.ClientConn
}

func NewPlatformClient(cc *grpc.ClientConn) PlatformClient {
	return &platformClient{cc}
}

func (c *platformClient) CreateExampleProject(ctx context.Context, in *ProjectInformation, opts ...grpc.CallOption) (*Executables, error) {
	out := new(Executables)
	err := c.cc.Invoke(ctx, "/proto.Platform/CreateExampleProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) BuildProject(ctx context.Context, in *TargetInformation, opts ...grpc.CallOption) (*Executables, error) {
	out := new(Executables)
	err := c.cc.Invoke(ctx, "/proto.Platform/BuildProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformClient) RunProject(ctx context.Context, in *RunInformation, opts ...grpc.CallOption) (*Executables, error) {
	out := new(Executables)
	err := c.cc.Invoke(ctx, "/proto.Platform/RunProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServer is the server API for Platform service.
type PlatformServer interface {
	CreateExampleProject(context.Context, *ProjectInformation) (*Executables, error)
	BuildProject(context.Context, *TargetInformation) (*Executables, error)
	RunProject(context.Context, *RunInformation) (*Executables, error)
}

func RegisterPlatformServer(s *grpc.Server, srv PlatformServer) {
	s.RegisterService(&_Platform_serviceDesc, srv)
}

func _Platform_CreateExampleProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).CreateExampleProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Platform/CreateExampleProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).CreateExampleProject(ctx, req.(*ProjectInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_BuildProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).BuildProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Platform/BuildProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).BuildProject(ctx, req.(*TargetInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Platform_RunProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServer).RunProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Platform/RunProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServer).RunProject(ctx, req.(*RunInformation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Platform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Platform",
	HandlerType: (*PlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExampleProject",
			Handler:    _Platform_CreateExampleProject_Handler,
		},
		{
			MethodName: "BuildProject",
			Handler:    _Platform_BuildProject_Handler,
		},
		{
			MethodName: "RunProject",
			Handler:    _Platform_RunProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform.proto",
}

func init() { proto.RegisterFile("platform.proto", fileDescriptor_platform_90d570a7a17b69c4) }

var fileDescriptor_platform_90d570a7a17b69c4 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0xc6, 0xf9, 0xd3, 0x26, 0xc7, 0xa5, 0xbf, 0x54, 0xb4, 0xfc, 0xb4, 0x6e, 0x8c, 0xe0, 0xab,
	0x50, 0x58, 0x2f, 0xd2, 0xc1, 0xc6, 0xd8, 0xcd, 0xba, 0x86, 0x51, 0x18, 0x5d, 0x30, 0x65, 0x8c,
	0x5e, 0x4d, 0x8d, 0x95, 0x44, 0x8b, 0x2d, 0x19, 0x59, 0x6e, 0xea, 0xa7, 0xd9, 0xeb, 0xec, 0x79,
	0xf6, 0x04, 0x43, 0xb2, 0x5c, 0x2b, 0x73, 0xb2, 0x2b, 0xeb, 0x7c, 0xe7, 0x9c, 0x4f, 0x47, 0xdf,
	0xf9, 0x0c, 0x87, 0x69, 0x4c, 0xd4, 0x5c, 0xc8, 0xe4, 0x3c, 0x95, 0x42, 0x09, 0xd4, 0x35, 0x9f,
	0xe0, 0x3b, 0xa0, 0xa9, 0x14, 0x3f, 0xe8, 0x4c, 0x5d, 0x73, 0x9d, 0x25, 0x8a, 0x09, 0x8e, 0x10,
	0x74, 0x38, 0x49, 0x28, 0xf6, 0x86, 0xde, 0xa8, 0x1f, 0x9a, 0x33, 0x7a, 0x01, 0xfd, 0x88, 0x49,
	0x3a, 0x53, 0x42, 0x16, 0xb8, 0x65, 0x12, 0x35, 0x80, 0x30, 0xec, 0xaf, 0x99, 0x98, 0x12, 0xb5,
	0xc4, 0x6d, 0x93, 0xab, 0xc2, 0xe0, 0x0e, 0x8e, 0xaf, 0x68, 0x4a, 0x79, 0x44, 0xf9, 0xac, 0xf8,
	0xcc, 0xf8, 0xea, 0x96, 0xc8, 0x05, 0x55, 0xfa, 0x8e, 0xb9, 0x14, 0x49, 0x75, 0x87, 0x3e, 0xa3,
	0x43, 0x68, 0x29, 0x61, 0xc9, 0x5b, 0x4a, 0xa0, 0x97, 0x00, 0x0f, 0x2c, 0x63, 0xf7, 0x2c, 0x66,
	0xaa, 0xb0, 0xc4, 0x0e, 0x12, 0xfc, 0xf6, 0x60, 0x50, 0x93, 0xd7, 0xc4, 0x8d, 0xe1, 0x11, 0x74,
	0x52, 0x3d, 0x5b, 0x49, 0x6d, 0xce, 0xe8, 0x18, 0xba, 0xf3, 0x98, 0x2c, 0x32, 0xdc, 0x1e, 0xb6,
	0x47, 0xfd, 0xb0, 0x0c, 0xd0, 0x10, 0xfc, 0x88, 0xce, 0x19, 0x67, 0x5a, 0x88, 0x0c, 0x77, 0x4c,
	0xce, 0x85, 0xd0, 0x08, 0xfe, 0x33, 0xa5, 0x5f, 0xeb, 0xc9, 0xba, 0x86, 0xf6, 0x6f, 0x18, 0xbd,
	0x86, 0x13, 0xa7, 0xd1, 0xa9, 0xdf, 0x33, 0xf5, 0xdb, 0x93, 0xfa, 0xd1, 0x4b, 0x4a, 0x22, 0x2a,
	0xbf, 0xf0, 0xb8, 0xc0, 0xfb, 0x43, 0x6f, 0xd4, 0x0b, 0x1d, 0x24, 0xf8, 0xd9, 0x81, 0xa3, 0xf2,
	0xa9, 0xee, 0xca, 0xae, 0x01, 0xa5, 0x8d, 0x45, 0x1a, 0x0d, 0xfc, 0xf1, 0xb3, 0x72, 0xe7, 0xe7,
	0xcd, 0x4d, 0x87, 0x5b, 0x9a, 0xf4, 0x00, 0xca, 0xf0, 0xdf, 0x68, 0x19, 0x4b, 0xc9, 0x1c, 0xa4,
	0xce, 0x3b, 0xeb, 0x76, 0x10, 0x74, 0x0a, 0xbd, 0xca, 0x6c, 0xb8, 0x63, 0xb2, 0x4f, 0xb1, 0x76,
	0xd1, 0x5c, 0x92, 0x84, 0xae, 0x85, 0x5c, 0x59, 0xd9, 0x6a, 0x40, 0x77, 0x2e, 0x89, 0x8c, 0xd6,
	0x44, 0x52, 0xab, 0xd1, 0x53, 0x5c, 0xaf, 0x6b, 0xff, 0x1f, 0xeb, 0xea, 0x35, 0xd7, 0x75, 0x03,
	0x07, 0x51, 0x65, 0x11, 0x46, 0x33, 0xdc, 0x1f, 0xb6, 0x47, 0xfe, 0xf8, 0xcc, 0x4a, 0xd2, 0x10,
	0xf2, 0xfc, 0xca, 0x29, 0x9e, 0x70, 0x25, 0x8b, 0x70, 0xa3, 0x1f, 0x7d, 0x82, 0x81, 0x1b, 0x6b,
	0x47, 0x63, 0x30, 0x9c, 0xcf, 0x2d, 0xe7, 0x36, 0xbb, 0x87, 0x8d, 0xa6, 0xd3, 0x6f, 0x70, 0xd4,
	0xb8, 0x0b, 0x0d, 0xa0, 0xbd, 0xa2, 0x85, 0xf5, 0xae, 0x3e, 0xa2, 0x57, 0xd0, 0x7d, 0x20, 0x71,
	0x5e, 0x2e, 0xc2, 0x1f, 0xff, 0xdf, 0xb8, 0xc4, 0x5e, 0x50, 0x56, 0xbd, 0x6b, 0xbd, 0xf5, 0x82,
	0x3b, 0x80, 0xc9, 0x23, 0x9d, 0xe5, 0x8a, 0xdc, 0xc7, 0x54, 0x4b, 0x34, 0x13, 0x49, 0x42, 0x78,
	0x74, 0x53, 0xff, 0x16, 0x2e, 0x84, 0xce, 0x60, 0x60, 0xc3, 0x0f, 0x72, 0x91, 0x27, 0x94, 0xab,
	0x0c, 0xb7, 0x8c, 0x92, 0x0d, 0x3c, 0xb8, 0x04, 0xbf, 0xe6, 0xce, 0xd0, 0x05, 0xf8, 0xb4, 0x0e,
	0xb1, 0x67, 0x84, 0x38, 0xb2, 0x33, 0xd6, 0x85, 0xa1, 0x5b, 0x15, 0xdc, 0xc2, 0x61, 0x98, 0xf3,
	0xdd, 0x96, 0xf3, 0x1a, 0x96, 0x0b, 0xe0, 0xa0, 0x32, 0xc2, 0x54, 0x48, 0x65, 0x4d, 0xb9, 0x81,
	0x8d, 0x7f, 0x79, 0xd0, 0x9b, 0x56, 0x3e, 0x9b, 0xc0, 0xf1, 0x47, 0x49, 0x89, 0xa2, 0x93, 0x47,
	0x92, 0xa4, 0x31, 0xb5, 0xd6, 0x47, 0xbb, 0x7f, 0x85, 0x53, 0xd4, 0x98, 0x3a, 0x43, 0xef, 0xe1,
	0xe0, 0x32, 0x67, 0x71, 0x54, 0xb5, 0xe3, 0x5d, 0xb6, 0xd9, 0xda, 0xfd, 0x06, 0x20, 0xcc, 0x79,
	0xd5, 0x7b, 0x62, 0x2b, 0x36, 0x9f, 0xbe, 0xad, 0xf1, 0x7e, 0xcf, 0x40, 0x17, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0x4b, 0x92, 0x2d, 0xb5, 0x05, 0x00, 0x00,
}
